name: Publish to gh-pages

On: 
   repository_dispatch: 
   push: 
     branches: 
       - master
       
jobs: 
   build: 
     runs-on: ubuntu latest
     steps: 
     - uses: actions/checkout@v2
     - name: Use Node.js
       uses: actions/setup-node@v1 
       with: 
         node-version: '12x' 
     - run: yarn
     - run: run yarn build
     - name: Deploy 
       uses: peaceiris/actions-gh-pages@v3
       with: 
         github_token: ${{ secrets.GITHUB_TOKEN }} 
         publish_dir: ./build
         
